### ISSUE TITLE
Add support for Shelly Plug S

### ISSUE THREAD

**Issue by ituri** [ituri/opendtu-widget#2]
API output:

```
{
  "wifi_sta": {
    "connected": true,
    "ssid": "changeME",
    "ip": "changeME",
    "rssi": -64
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "mqtt": {
    "connected": false
  },
  "time": "10:40",
  "unixtime": 1689324013,
  "serial": "changeME",
  "has_update": false,
  "mac": "3CE90ED3A556",
  "cfg_changed_cnt": 0,
  "actions_stats": {
    "skipped": 0
  },
  "relays": [
    {
      "ison": true,
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "overpower": false,
      "source": "http"
    }
  ],
  "meters": [
    {
      "power": 62.19,
      "overpower": 0,
      "is_valid": true,
      "timestamp": 1689331213,
      "counters": [
        60.141,
        61.448,
        58.828
      ],
      "total": 171494
    }
  ],
  "temperature": 32.48,
  "overtemperature": false,
  "tmp": {
    "tC": 32.48,
    "tF": 90.47,
    "is_valid": true
  },
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20230503-101129/v1.13.0-g9aed950",
    "old_version": "20230503-101129/v1.13.0-g9aed950"
  },
  "ram_total": 52056,
  "ram_free": 39348,
  "fs_size": 233681,
  "fs_free": 166162,
  "uptime": 191368
}
```

**Comment by ituri** [comment]
cc @xssociety

Probier mal aus, ob alles klappt. Falls es dir gefällt: https://www.paypal.com/donate/?hosted_button_id=25AMUKSUVDSYQ

**Comment by xssociety** [comment]
Das ist das Ergebnis 

![IMG_2394](https://github.com/ituri/opendtu-widget/assets/74319891/f6d7c1b6-8891-4dc1-8736-130c3ace282e)

**Comment by ituri** [comment]
Kannst du bitte einmal das ganze Script posten?

**Comment by xssociety** [comment]
Kommt aber noch ne Fehler Meldung. 

Hier das Script:

const dtuApiUrl = "http://192.168.XXX.XX/api/livedata/status"; // API endpoint for OpenDTU
const dtuUser = "changeMe"; // replace with actual username for dtuApiUrl
const dtuPass = "changeMe"; // replace with actual password for dtuApiUrl

const powermeter = "tasmota"; // Choose between "tasmota" or "shelly"

// Tasmota configuration
const tasmotaApiUrl = "http://change-me/cm?cmnd=status%208"; // API endpoint for Tasmota
const tasmotaUser = "changeme"; // replace with actual username for tasmotaApiUrl
const tasmotaPass = "changeme"; // replace with actual password for tasmotaApiUrl

// Shelly configuration
const shellyApiUrl = "http://192.168.XXX.XX/"; // API endpoint for Shelly
const shellyUser = "changeme"; // replace with actual username for shellyApiUrl
const shellyPass = "changeme"; // replace with actual password for shellyApiUrl

const showPowerDraw = 1;
const powerDrawThreshold = 0;

const redThreshold = 220;
const yellowThreshold = 260;
const greenThreshold = 400;

async function fetchData(apiUrl, username, password) {
  let request = new Request(apiUrl);
  const auth = `${username}:${password}`;
  const base64Auth = btoa(auth);
  request.headers = {
    Authorization: `Basic ${base64Auth}`,
  };

  try {
    let response = await request.loadJSON();
    return response;
  } catch (error) {
    console.error(`Could not fetch data: ${error}`);
    return null;
  }
}

// Helper function to retrieve power draw value from the API response
function getPowerDrawValue(powerDrawData) {
  if (powermeter === "tasmota") {
    // Handle Tasmota API response structure
    if (
      powerDrawData &&
      powerDrawData.StatusSNS &&
      powerDrawData.StatusSNS.hasOwnProperty("")
    ) {
      return parseFloat(powerDrawData.StatusSNS[""]["current"]) || 0;
    }
  } else if (powermeter === "shelly") {
    // Handle Shelly API response structure
    if (
      powerDrawData &&
      powerDrawData.meters &&
      powerDrawData.meters.length > 0
    ) {
      return parseFloat(powerDrawData.meters[0].power) || 0;
    }
  }
  return 0;
}

async function createWidget(data, powerDrawData) {
  let widget = new ListWidget();

  let startColor = new Color("#434C5E");
  let endColor = new Color("#2E3440");
  let gradient = new LinearGradient();
  gradient.colors = [startColor, endColor];
  gradient.locations = [0, 1];
  widget.backgroundGradient = gradient;

  let title = widget.addText("OpenDTU☀️");
  title.textColor = Color.white();
  title.font = Font.boldSystemFont(16);

  let powerData = parseFloat(data.inverters[0].AC["0"].Power.v);
  let yieldDayData = (
    parseFloat(data.inverters[0].AC["0"].YieldDay.v) / 1000
  ).toFixed(2);
  let yieldTotalData = parseFloat(
    data.inverters[0].AC["0"].YieldTotal.v
  ).toFixed(2);

  widget.addSpacer(2);

  let gridStack = widget.addStack();
  gridStack.layoutHorizontally();

  let leftStack = gridStack.addStack();
  leftStack.layoutVertically();

  let powerLabel = leftStack.addText(`Power:`);
  powerLabel.textColor = Color.white();
  powerLabel.font = Font.systemFont(8);

  let powerText = leftStack.addText(`${powerData.toFixed(2)} W`);
  powerText.font = Font.systemFont(13);
  if (powerData < redThreshold) {
    powerText.textColor = Color.red();
  } else if (powerData >= redThreshold && powerData < yellowThreshold) {
    powerText.textColor = Color.yellow();
  } else {
    powerText.textColor = Color.green();
  }

  let yieldDayLabel = leftStack.addText(`Yield Day: `);
  yieldDayLabel.textColor = Color.white();
  yieldDayLabel.font = Font.systemFont(8);

  let yieldDayText = leftStack.addText(`${yieldDayData} kWh  `);
  yieldDayText.textColor = Color.white();
  yieldDayText.font = Font.systemFont(13);

  let rightStack = gridStack.addStack();
  rightStack.layoutVertically();

  if (showPowerDraw) {
    let powerDrawDataValue = powerDrawData
      ? getPowerDrawValue(powerDrawData)
      : 0;

    let powerDrawLabel = rightStack.addText(`Power Draw: `);
    powerDrawLabel.textColor = Color.white();
    powerDrawLabel.font = Font.systemFont(8);
    let powerDrawText = rightStack.addText(`${powerDrawDataValue} W`);
    powerDrawText.font = Font.systemFont(13);

    if (powerDrawDataValue > powerDrawThreshold) {
      powerDrawText.textColor = Color.yellow();
    } else {
      powerDrawText.textColor = Color.green();
    }
  }

  const dcOutputs = data.inverters[0].DC;
  for (let key in dcOutputs) {
    let dcName = dcOutputs[key].name.u;
    let dcPower = parseFloat(dcOutputs[key].Power.v);

    let dcLabel = rightStack.addText(`${dcName}: `);
    dcLabel.textColor = Color.white();
    dcLabel.font = Font.systemFont(8);

    let dcText = rightStack.addText(`${dcPower.toFixed(2)} W`);
    dcText.font = Font.systemFont(13);
    dcText.textColor = Color.white();
  }

  let yieldTotalLabel = leftStack.addText(`Yield Total: `);
  yieldTotalLabel.textColor = Color.white();
  yieldTotalLabel.font = Font.systemFont(8);

  let yieldTotalText = leftStack.addText(`${yieldTotalData} kWh`);
  yieldTotalText.textColor = Color.white();
  yieldTotalText.font = Font.systemFont(13);

  widget.addSpacer();
  let timeStampStack = widget.addStack();
  timeStampStack.layoutVertically();
  timeStampStack.addSpacer();
  let dateText = timeStampStack.addDate(new Date());
  dateText.textColor = Color.white();
  dateText.applyRelativeStyle();
  dateText.font = Font.systemFont(8);
  let agoText = timeStampStack.addText(" ago");
  agoText.textColor = Color.white();
  agoText.font = Font.systemFont(8);

  return widget;
}

// Main script
async function run() {
  try {
    let data = await fetchData(dtuApiUrl, dtuUser, dtuPass);
    let powerDrawData = showPowerDraw
      ? await fetchData(
          powermeter === "tasmota" ? tasmotaApiUrl : shellyApiUrl,
          powermeter === "tasmota" ? tasmotaUser : shellyUser,
          powermeter === "tasmota" ? tasmotaPass : shellyPass
        )
      : null;

    let widget = await createWidget(data, powerDrawData);

    if (config.runsInWidget) {
      Script.setWidget(widget);
    } else {
      widget.presentMedium();
    }
  } catch (error) {
    console.error(error.message);
    let widget = new ListWidget();
    widget.addText("Error: Unable to connect to powermeter");
    if (config.runsInWidget) {
      Script.setWidget(widget);
    } else {
      widget.presentMedium();
    }
  }
}

await run();


Hier die Fehlermeldung:

2023-07-16 20:53:23: Could not fetch data: Error: Es wurde kein Server mit dem angegebenen Hostnamen gefunden.

**Comment by xssociety** [comment]
Die API URL vom Shelly wäre HTTP://XXX.XXX.XXX.XX/status 

da kommt dann die Ausgabe von ganz oben.

**Comment by ituri** [comment]
Hast Du denn auch das /status in der shellyApiUrl angehängt? Du hast es zwar zensiert, aber das /status fehlt völlig. 

Außerdem müsstest du noch die variable powermeter auf shelly stellen; in deinem Code steht sie auf tasmota. 

Falls es weiterhin nicht geht, bitte nochmal Fehlermeldung und Code posten.

**Comment by xssociety** [comment]
Jetzt müsste nur noch die Größe angepasst werden. Rest geht alles   

![IMG_2398](https://github.com/ituri/opendtu-widget/assets/74319891/02cf0266-1961-4cbc-b2be-ac1336654637)

vielleicht eine dritte Spalte?

**Comment by ituri** [comment]
> vielleicht eine dritte Spalte?

Das ist mit dem jüngsten Commit jetzt auch implementiert.
![CleanShot 2023-07-16 at 21 35 13](https://github.com/ituri/opendtu-widget/assets/871297/204929a7-2e0a-4a74-8d8d-5fa213a3c260)

**Comment by xssociety** [comment]
Läuft! Super vielen Dank. Könnte man den Abstand zwischen den Spalten noch vergrößern?

**Comment by ituri** [comment]
> Läuft! Super vielen Dank. Könnte man den Abstand zwischen den Spalten noch vergrößern?

Klar. Such dir im Code einfach die Stellen, wo die Einheiten angehängt werden. Hinter der Einheit dann einfach ein paar Leerzeichen einfügen, z.B. in Zeile 128 für den Abstand zwischen der zweiten und dritten Spalte.

**Comment by ituri** [comment]
Und nochmal umgebaut; jetzt sind alle Daten des Wechselrichters auf einer Seite.
![screenshot](https://github.com/ituri/opendtu-widget/raw/main/screenshots/screenshot-medium.jpg)

**Comment by xssociety** [comment]
Leider passt der der Abstand nicht vom Shelly. Was muss ich ändern damit dieser weiter nach rechts rutscht. 
Vielleicht so definieren invertier linksbündig, String mittig und Shelly rechtsbündig 
![IMG_2403](https://github.com/ituri/opendtu-widget/assets/74319891/65fc3435-c58a-448b-ba0b-d20f80264ca5)

**Comment by ituri** [comment]
Das geht in scriptable nicht. 
Aktualisiere auf die neuste Version des Widgets, da sollten die Abstände passen. Wenn nicht, nochmal melden.

**Comment by xssociety** [comment]
Leider ohne Erfolg. Ist kein Platz dazwischen. Sorry.

**Comment by ituri** [comment]
Okay. 

Dann such dir diese Zeile:
```
let dcText = dcStack.addText(`${dcPower.toFixed(2)} W`)
```

Müsste Zeile 136 sein. Direkt hinter dem W so viele Leerzeichen setzen, dass es vom Abstand her passt.

**Comment by xssociety** [comment]
Passt super vielen Dank!
