### ISSUE TITLE
Widget startet nicht

### ISSUE THREAD

**Issue by Nickel1893** [ituri/opendtu-widget#4]
Hallo ituri,

ich bekomm deine Widgets leider nicht ans laufen. Kannst du mich bitte ein bisschen supporten?
Frage 1: läuft das Widget auch ohne Tasmota und / oder Shelly?
Frage 2: was hat es mit der iCloud Datei zu tun? Muss ich hier die IP abändern?
Frage 3: in welcher Zeile muss ich in dem Script was annpassen? 16 - 18? Also IP, User und Passwort?

Danke schonmal :)

**Comment by ituri** [comment]
Hallo,

beim ersten Aufruf wird die `opendtu-config.json` in der iCloud erstellt. Dort musst du alle Einstellungen ändern; im Script selber nicht. Du kannst `showPowerDraw` auf 0 setzen, dann wird erst gar nicht versucht, Daten von einem Shelly oder Tasmota zu beziehen.

**Comment by Nickel1893** [comment]
Super, vielen Dank. Nun hat es funktioniert. Ich wusste nicht wie ich die opendtu-config.json bearbeiten kann. Mit der App jayson ging dies jetzt problemlos. 
Widgets laufen, vielen Dank.
