### ISSUE TITLE
undefined is not an object (evaluating 'data.inverters[0].AC["0"]')

### ISSUE THREAD

**Issue by BabyFnord** [ituri/opendtu-widget#5]
Moinsen,

bei einer Erstinstallation von Scriptable und `opendtu-widget` für eine zuverlässig laufende OpenDTU mit der aktuellen FW [v24.2.12](https://github.com/tbnobody/OpenDTU/releases/tag/v24.2.12) erscheint die Fehlermeldung:

> Errors Logged: undefined is not an object (evaluating 'data.inverters[0].AC["0"]')

und zusätzlich
> Error: Unable to connect to powermeter

Ein Powermeter ist derzeit nicht vorhanden, der Output der Web API sieht so aus:
`{"inverters":[{"serial":"xxx1","name":"O","order":0,"data_age":6,"poll_enabled":true,"reachable":true,"producing":true,"limit_relative":100,"limit_absolute":800},{"serial":"xxx2","name":"S","order":0,"data_age":1,"poll_enabled":true,"reachable":true,"producing":true,"limit_relative":100,"limit_absolute":700}],"total":{"Power":{"v":185.2000122,"u":"W","d":1},"YieldDay":{"v":842,"u":"Wh","d":0},"YieldTotal":{"v":955.4649658,"u":"kWh","d":3}},"hints":{"time_sync":false,"radio_problem":false,"default_password":false}}`

Was könnte hier das Problem sein? 🤔

**Comment by ituri** [comment]
Hallo Patrick,

ja, das ist richtig. Durch [den breaking change](https://github.com/tbnobody/OpenDTU/commit/c27ecc3620f656fbdfaa7e9f0f3deca6a371a373) im neuesten OpenDTU-release hat sich einiges an der API geändert. Es muss nun `?inv=<serial number>` an die URL gehängt werden, um weiterhin detaillierte Informationen zu bekommen. Der normale API call gibt angeblich nur noch wenige Informationen zurück, wobei die ja ausreichen sollten, wenn ich mir deinen Output angucke.
Ich habe momentan nicht allzu viel Zeit mich um einen Fix zu kümmern und auch das neue Update nicht installiert. Für's erste kannst du versuchen, die `dtuApiUrl` wie oben angegeben zu erweitern. 

Ansonsten nehme ich auch gerne PRs an. :-)

**Comment by BabyFnord** [comment]
Hallo P.,
das sieht nicht nach einer Methode aus, zwei Inverter zu pollen. Danke für den PR Invite, hier fehlen die nötigen JS Skills, mich in fremden Code reinzuarbeiten.

Alles Gute!

**Comment by ituri** [comment]
Habe dann doch mal das Update durchgeführt. Das kleine Widget läuft ja weiterhin, da es nicht die Daten der einzelnen Strings abfragt. 
Für das medium widget ist seit dem OpenDTU-Update nun zusätzlich die Angabe der Seriennummer des Wechselrichters notwendig. Die muss in der `opendtu-config.json` hinterlegt werden. Mit der [neusten Version](https://github.com/ituri/opendtu-widget/commit/afec0bc35c048608c640bcd3560945f506dbc846) des Widgets sollte dann auch wieder alles angezeigt werden und der Fehler verschwinden, vorausgesetzt die Seriennummer ist hinterlegt.

Achtung: Bitte auf das / am Ende der `dtuApiUrl` achten!

**Comment by BabyFnord** [comment]
Danke für das Update, @ituri! Zwei Fragen noch: 
- Pro Widget nur ein Inverter, richtig? Bei zwei Invertern folglich zwei Widgets? Dann bräuchte es zwei configs, damit das für einen Inverter spezifische Widget in Codezeile 4 z. B. ein eigene Konfiguration liest `const configFileName = "opendtu-config-[SERIAL].json"  ;`? Oder habe ich was übersehen, dass ein Widget auch zwei Inverter pollt?
- Anders als in deinem Screenshot erscheinen Strings ohne Namen, vor dem Doppelpunkt erscheinen keine Angaben. Für die Strings ist vermutlich dieser Codeblock zuständig
```
    let dcName = dcOutputs[key].name.u;
    let dcPower = parseFloat(dcOutputs[key].Power.v);
```
Ist hier vorgesehen, Strings als »String [n]: [Wert] [Einheit]« anzuzeigen? Im Screenshot sieht es danach auch … 🤷

**Comment by ituri** [comment]
> * Pro Widget nur ein Inverter, richtig? Bei zwei Invertern folglich zwei Widgets? Dann bräuchte es zwei configs, damit das für einen Inverter spezifische Widget in Codezeile 4 z. B. ein eigene Konfiguration liest `const configFileName = "opendtu-config-[SERIAL].json"  ;`? Oder habe ich was übersehen, dass ein Widget auch zwei Inverter pollt?

Ganz richtig. Mangels mehrerer Wechselrichter kann ich das hier leider auch nicht testen. Aber ja, es sollte mit einer anders benannten Kopie des Scripts und der Konfigurationsdatei funktionieren.

> * Anders als in deinem Screenshot erscheinen Strings ohne Namen, vor dem Doppelpunkt erscheinen keine Angaben. Für die Strings ist vermutlich dieser Codeblock zuständig
> 
> ```
>     let dcName = dcOutputs[key].name.u;
>     let dcPower = parseFloat(dcOutputs[key].Power.v);
> ```
> 
>  Ist hier vorgesehen, Strings als »String [n]: [Wert] [Einheit]« anzuzeigen? Im Screenshot sieht es danach auch … 🤷

Nein, hier sollte der volle Stringname aus OpenDTU angezeigt werden. Im medium widget funktioniert das bei mir auch einwandfrei, gerade nochmal getestet. Mein erster String heißt in OpenDTU z.B. "String 1 - Garten rechts" und wird auch als solcher angezeigt. Die Nummerierung habe ich manuell durch meine eigene Benennung in OpenDTU vorgenommen.

**Comment by BabyFnord** [comment]
Jetzt ist alles klar und läuft, danke!
